# Generated by Django 2.2.1 on 2019-05-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
